[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:3000"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS","PATCH"
    